### PR TITLE
Use label for validation messages

### PR DESCRIPTION
**Pull request by lalov**
Changed the validation logic to use field->label for validation messages. 

Also fixed a casing error for InvalidArrayFieldType, though that should maybe be a second pull request...

### CODE REVIEW

**Comment by tanthammar** [comment]
Thank you. 

I have one concern. 

There are currently 200+ downloads of this package.

I would like this to be an optional way to handle translations. I worry that a lot of users might have spent time on creating translation files (as I've done) and suddenly we change how this is handled. 

That would be a "breaking" change...

Do you have a suggestion on how to make this an option, without making it to heavy?

**Comment by tanthammar** [comment]
Don't get me wrong, I think this is the right way to go, I just want to make a smooth transition for other users.

**Comment by tanthammar** [comment]
Supposedly, users with multilingual apps already have their labels translated ...?

**Comment by tanthammar** [comment]
@lalov I will close this PR as it is implemented in v4.4.0

Check out the wiki https://github.com/tanthammar/tall-forms/wiki/BaseField-Validation#component-validation-attributes

Had to make some adjustments.

**Comment by lalov** [comment]
Thanks, that's great!
Another solution might have been to make each field aware of if the lable was set explicitly or not.

BaseField.php :

<pre>
    public $isTranslated = false;

    public function __construct($label, $key)
    {
        $this->label = $label;
        if(isset($key)){
            $this->isTranslated = true;
        }
        $this->name = $key ?? \Str::snake(\Str::lower($label));
        $this->key = 'form_data.' . $this->name;
        $this->setAttr();
    }
</pre>

And then modifiy the attributes() funcition to check the isTranslated parameter. 

But I think your solution is better. 
Thanks again! (sorry if this reopens the pull request...)

**Comment by tanthammar** [comment]
@lalov check out v4.4.1, I added the option to override, per field.

**Pull request closed without merging**
