### PR TITLE
Fixed: Hide form title if empty

### PR DESCRIPTION
**Pull request by danielbehrendt**

### CODE REVIEW

**Comment by tanthammar** [comment]
I am not sure this is needed.

If the formTitle is omitted  or = "" or  = null, it does not take any height of the window.
If I make this change I still get an empty `<h3>` if spaLayout is true.

I played around with it when creating the form layout and I like to remove unnecessary code  ...

But If it is important to you I will accept the change?

**Comment by danielbehrendt** [comment]
In my case it took some space 
Bildschirmfoto 2020-08-20 um 09 13 56

**Comment by danielbehrendt** [comment]
You're right, it must be:

`@if(!$spaMode && $formTitle) <h3 class="text-2xl my-4">{{$formTitle}}</h3> @endif`

Maybe you can change this directly in your repo?

**Comment by tanthammar** [comment]
Yes. I'll add it later today together wit a fix for the file upload.

**Comment by tanthammar** [comment]
I closed this because I implemented your request

**Pull request closed without merging**
