### PR TITLE
new: after icons & suffix

### PR DESCRIPTION
**Pull request by mertasan**
for: #60

### CODE REVIEW

**Comment by tanthammar** [comment]
Thank you for your help!

I released a slightly different version inspired by yours, so I am closing this PR.
(The position of the error icon was incorrect)

**Comment by mertasan** [comment]
Thank you. 

By the way: 
You can request an arrangement. You can then apply your own changes and publish a version. My last 3-4 PR were rejected for the same reason. If you do it this way, nobody will rise in the contributor list. :))

**Comment by tanthammar** [comment]
@mertasan Apologies.
I didn't think of it in that way.

You are already no1 in my mind :)

**Comment by mertasan** [comment]
No need to apologize. GitHub is also like a career history. Therefore I care. Thanks:)

**Pull request closed without merging**
