### PR TITLE
Nested KeyVal fields

### PR DESCRIPTION
**Pull request by danielbehrendt**
@tanthammar you can test the nested `KeyVal`fields with the following:

Create a custom field:

```
<?php

namespace App\View;

use Tanthammar\TallForms\KeyVal;

class CustomKeyVal extends KeyVal
{
    public $allowed_in_array = true;
}

```
and then used it:

```
[
    KeyVal::make('Nested')->fields([
        \App\View\CustomKeyVal::make('Names')->fields([
            Input::make('Deutsch', 'de')->rules('required'),
            Input::make('English', 'en')->rules('required'),
        ]),
    ]),
]
```

### CODE REVIEW

**Comment by tanthammar** [comment]
Hi @danielbehrendt 

Thank you for your PR AND the time you spent on it.

I don't have the time to focus this topic at the moment.
Is it ok if you keep it in your fork for the time being?

I will get to it, it's just that I have to create some more fields first.

Still a bit concerned about the large amount of re-loops, want to test it myself before merging.

At a quick glance it looks ok !

**Comment by danielbehrendt** [comment]
Hi @tanthammar,

> Is it ok if you keep it in your fork for the time being?

this is absolutely ok.

> Still a bit concerned about the large amount of re-loops, want to test it myself before merging.

I know what you mean but this way it works no matter how deep the fields are nested. In my tests the recursions where really robust and I didn't get any endless loops.

```
KeyVal::make('Level 1')->fields([
    Input::make('Name 1'),
    CustomKeyVal::make('Level 2')->fields([
        Input::make('Name 2')->rules('required'),
        CustomKeyVal::make('Level 3')->fields([
            Input::make('Name 3')->rules('required'),
        ]),
    ]),
])
```
One thing that doesn't work for now is nesting repeaters (or `Repeater` in `KeyVal` fields) but I think that's a real special case.

**Comment by tanthammar** [comment]
@danielbehrendt Don't know if you follow me on twitter, but there is a bit of a hassle to keep this package alive.
Just want to let you know that I am doing all a can to keep it open.
Would hate to close it down.

**Comment by danielbehrendt** [comment]
No I do :) What's the exact problem?

**Comment by tanthammar** [comment]
https://twitter.com/TinaHammar/status/1317459883973804033

**Comment by tanthammar** [comment]
@danielbehrendt do you still need this?

I'm ready to tackle the task. Done with all the basic fields.
Have you tested this on v5.x?

**Comment by danielbehrendt** [comment]
@tanthammar Yes, I still need this. I've update it yesterday (works with 5.x) to make nested repeaters work. Please have a look and tell me what you think.

**Comment by tanthammar** [comment]
@danielbehrendt 
Can you please update to match v5.2.3.

It solves errors with realtime validation for Repeater and KeyVal fields.


Please test your branch with realtime validation for scenarios where the `$field->key` could become `form_data.nested.name.de` and `form_data.nested.last_name.de` in the same form.
It must be possible to differentiate realtime validation for the cases your implementation may create.

(Also, if possible, create a version without merge conflicts)

**Comment by danielbehrendt** [comment]
@tanthammar Fixed and merged. Could you please try again?

**Comment by tanthammar** [comment]
I did only one test.
Played with levels.
(Did not extend the KeyVal field, I just temprarily changed `$allowed_in_array = true`)
 
```
 KeyVal::make('Customer')->fields([
                KeyVal::make('Company name')->fields([
                    Input::make('Deutch', 'de')->rules('required|one'),
                    Input::make('English', 'en')->rules('required|two'),
                ]),
                KeyVal::make('Description')->fields([
                    Textarea::make('Deutch', 'de')->rules('required|three'),
                    Textarea::make('English', 'en')->rules('required|four'),
                    KeyVal::make('Address')->fields([
                        Input::make('Street')->rules('required|in:five'),
                        KeyVal::make('Area')->fields([
                            Input::make('City')->rules('required|in:six'),
                            Input::make('Country')->rules('required|in:seven'),
                        ]),
                    ]),
                ]),
            ])
```

Error:
1. Realtime validation doesn't work. "Method Illuminate\Validation\Validator::validate... doesn't exist" 
2. Hitting submit button clears all values in the inputs.

**Comment by danielbehrendt** [comment]
@tanthammar I will check this

**Comment by danielbehrendt** [comment]
@tanthammar Did you use my repo?

**Comment by tanthammar** [comment]
Yes

**Comment by tanthammar** [comment]
OH, I see I'm tired... the validation values are all wrong ... Sorry, my bad!!
I'll test again.

**Comment by tanthammar** [comment]
@danielbehrendt 
Sorry for giving you such a hard time on this.
- I invited you as a collaborator to this repo.
- I did some additional updates for validation, finally got the labels as attributes working for Repeater. see v5.2.4
- I created a new branch, `nested-keyval`. 
   - can you please checkout and merge your PR to that branch. (update for 5.2.4)

It's easier to collaborate this way 👍 
OK?
(Hope you did see my message that it was my fault that the tests failed)

Will start testing as soon as I hear from you, that you pulled in your changes.

**Comment by danielbehrendt** [comment]
@tanthammar No problem, the suggested workflow seems also easier to me. I've implemented the changes from 5.2.4 in my local branch and one thing I've already noticed is that renamed the function `get_rules` to `rules`. As a result of this all `$this->models->exists` (in `rules` of my own form classes) has to changed to `optional($this->model)->exists` otherwise I get an exception when trying to validate/submit:

```
ErrorException
Trying to get property 'exists' of non-object
```

**Comment by tanthammar** [comment]
No that should not need to change.

**Comment by danielbehrendt** [comment]
Hm, strange. I get an exception and wrapping it in `optional()` removes the exception.

**Comment by danielbehrendt** [comment]
@tanthammar seems `if (method_exists($this, 'rules')) return $this->rules();` is getting called before `$this->model` is populated.

**Comment by tanthammar** [comment]
That's really bad if that's the case. I didn't get that error in my tests. Not at the office now. Will check soon. If so, I'll have to back the last release. 

You have access - can you help me remove the last release? So no one else gets this problem. 

Can re-release in a few hours once I've performed new tests. 

Can you remove the release ?

Om my phone...

**Comment by tanthammar** [comment]
Or try adding public property $rules = []; to TallForms trait. That might solve it.

**Comment by tanthammar** [comment]
@danielbehrendt 
I'm back at the office again. 
I do not get any errors related to $this->model->exists.
Can you give me some pastable code so I can reproduce it.

**Comment by danielbehrendt** [comment]
@tanthammar adding `public $rules = [];` doesn't fix the error.

**Comment by tanthammar** [comment]
Can you give me something to copy/paste to reproduce?

**Comment by danielbehrendt** [comment]
> Can you give me something to copy/paste to reproduce?

Yes, I do. Maybe this is only in combination with my changes? Should I merge everything  in nested-keyval branch and provide you some testing code?

**Comment by tanthammar** [comment]
Yes please :) I'll wait here for a ping.

What is your name on Discord? I can invite you to a private channel, easier to chat.

**Comment by tanthammar** [comment]
@danielbehrendt 
I tested these, none of them return an error for me.

```php
    public function beforeFormProperties()
    {
        dd($this->model->exists);
    }
    public function afterFormProperties()
    {
        dd($this->model->exists);
    }
```

**Comment by danielbehrendt** [comment]
This is where I get an error:

```
public function fields()
{
    return [
        Input::make('Name')
            ->rules(
                $this->model->exists ? 'required|unique:shops,name,' . $this->model->id : 'required|unique:shops,name'
            ),
        Input::make('Frontend URL'),
    ];
}
```

**Comment by tanthammar** [comment]
I added this to my form, no errors.

```php
Input::make('Name')->rules($this->model->exists ? 'required|unique:shops,name,' . $this->model->id : 'required|unique:shops,name');
```
Must be something with your model binding

**Comment by tanthammar** [comment]
Are you on master or your own fork?

**Comment by tanthammar** [comment]
Also tested this example from the docs: https://github.com/tanthammar/tall-forms/wiki/BaseField-Validation#conditional-rules-in-field-declaration

no errors for me.

**Comment by danielbehrendt** [comment]
> Are you on master or your own fork?

On my fork

**Comment by tanthammar** [comment]
- Do you have a Discord name?
- Can you check out master branch to test if you still have errors?

**Comment by danielbehrendt** [comment]
> * Do you have a Discord name?

danielbehrendt#4977

**Comment by danielbehrendt** [comment]
> * Can you check out master branch to test if you still have errors?

Same on your master branch. 

I'll noticed that you mentioned to use `optional($this->model)->exists` (which makes it work for me) instead of `$this->model->exists` in the docs 

https://github.com/tanthammar/tall-forms/wiki/BaseField-Validation#conditional-rules-in-field-declaration

but I wonder why it seems to work without `optional()`for you?

**Comment by tanthammar** [comment]
@danielbehrendt
- I finally got the same error, when I added a Spatie tags field. Released v5.2.5 (master branch)
- unable to find you on discord. Can I send you a dm on twitter instead? Or dm me on twitter `@TinaHammar`
-But Spatie tags has broken so I need to pay it some attention. Not sure what is going on.

**Comment by tanthammar** [comment]
@danielbehrendt 
Now I know why Spatie tags broke:
https://github.com/livewire/livewire/issues/1982

**Comment by tanthammar** [comment]
Closing. We're handling this via branch

**Pull request closed without merging**
